#pragma once
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <string>
#include <vector>
#include <iostream>
#include <stdint.h>
#include <cmath>
#include <array>
#include <sstream>
#include <algorithm>
#include <iomanip>
#include <psapi.h>